### ISSUE TITLE
eror #promote

### ISSUE THREAD

**Issue by ghost** [TobyG74/ElainaBOT#21]
[EXEC] 30/11 09:21:55 #promote from ~Liy in ☠️T o x i c S q u a d☠️
[ERROR] Error: Evaluation failed: n
    at ExecutionContext._evaluateInternal (C:\ElainaBOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\ElainaBOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

**Comment by ghost** [comment]
saya hannya memberitahukan saja ;v

**Comment by TobyG74** [comment]
#promote @tagmembernya, ini command digunain buat jadiin orang admin grup
