### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by ghost** [TobyG74/ElainaBOT#24]
[ERROR] TypeError: Cannot read property 'match' of undefined
    at tobz (C:\ElainaBOT\tobz.js:358:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

EXEC] 01/12/20 10:24:47 #randomhentai [1] from DEEP WEB [shadows] in Uji Coba Bot Whatsapp
[ERROR] TypeError: Cannot read property 'url' of undefined
    at tobz (C:\ElainaBOT\tobz.js:938:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[EXEC] 01/12/20 10:25:13 #randomnsfwneko [1] from DEEP WEB [shadows] in Uji Coba Bot Whatsapp
[ERROR] TypeError: Cannot read property 'endsWith' of undefined
    at tobz (C:\ElainaBOT\tobz.js:953:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[EXEC] 01/12/20 10:25:48 #randomtrapnime [1] from DEEP WEB [shadows] in Uji Coba Bot Whatsapp
[ERROR] TypeError: Cannot read property 'result' of undefined
    at tobz (C:\ElainaBOT\tobz.js:923:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by TobyG74** [comment]
join grup wa.
