### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MrG3P5** [TobyG74/ElainaBOT#25]
masa pas udah run botnya bekerja dah?

**Comment by TobyG74** [comment]
Maksudnya gmn?

**Comment by idkmew** [comment]
Error bang error yg pertama :
- Error: Cannot find module 'macos-release'
trus aku apus tu macos-releaseny, trus muncul lagi error
- Error: Cannot find module 'windows-release'
Terpaksa aku apus lagi, dan aku pikir berjalan lancar eh malah muncul error lagi 
ReferenceError: winRelease is not defined
    at osName (D:\MathType\Whatsapp\BotTester\ElainaBOT-main\node_modules\os-name\index.js:41:3)
    at D:\MathType\Whatsapp\BotTester\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:171:26
    at step (D:\MathType\Whatsapp\BotTester\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (D:\MathType\Whatsapp\BotTester\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (D:\MathType\Whatsapp\BotTester\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
Ad solusi?

**Comment by TobyG74** [comment]
Itu error bukan karena file bot nya, coba install nya di disk C, jgn D

**Comment by restugbk** [comment]
nitip https://api.i-tech.id/
