### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by idkmew** [TobyG74/ElainaBOT#43]
√ Browser Launched
Error: Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (C:\ElainaBOT-main\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\ElainaBOT-main\node_modules\execa\index.js:188:17)
    at windowsRelease (C:\ElainaBOT-main\node_modules\windows-release\index.js:39:19)
    at osName (C:\ElainaBOT-main\node_modules\os-name\index.js:43:18)
    at C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:171:26
    at step (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  shortMessage: 'Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  command: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'powershell' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Gmna ya cara ngatasinya?

**Comment by TobyG74** [comment]
Coba run pake cmd

**Comment by idkmew** [comment]
> Coba run pake cmd

yah itu make cmd bang :'(00

**Comment by TobyG74** [comment]
Coba join grup wa aja, blm pernah ngalamin soalnya

**Comment by idkmew** [comment]
> Coba join grup wa aja, blm pernah ngalamin soalnya

bisa minta link kh bang?

**Comment by TobyG74** [comment]
Di readme ada
