### ISSUE TITLE
C:\ElainaBOT-main\tobz.js:869         case '#group':         ^^^^  SyntaxError: Unexpected token 'case'     at Module._compile (internal/modules/cjs/loader.js:892:18)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)     at Module.load (internal/modules/cjs/loader.js:812:32)     at Function.Module._load (internal/modules/cjs/loader.js:724:14)     at Module.require (internal/modules/cjs/loader.js:849:19)     at require (internal/modules/cjs/helpers.js:74:18)     at Object.<anonymous> (C:\ElainaBOT-main\index.js:14:1)     at Module._compile (internal/modules/cjs/loader.js:956:30)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)     at Module.load (internal/modules/cjs/loader.js:812:32) npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#62]
nih kenapa dah

**Comment by fairyenzy** [comment]
emm, sama nih saya juga error disitu

**Comment by akujeleksad** [comment]
iya

**Comment by TobyG74** [comment]
Fixed
