### ISSUE TITLE
help padahal udah install imagemagick 1.2.3.5.6

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#77]
[EXEC] 15/12/20 12:21:37 #magernulis1 [3] from OWNERN҉O҉T҉B҉O҉T҉ in NOT BOT GRUP #1
(node:42300) UnhandledPromiseRejectionWarning: Error: Cannot find file. Make sure the file reference is relative, a valid URL or a valid DataURL
    at Client.<anonymous> (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:916:35)
    at step (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:900:16)
    at ChildProcess.<anonymous> (C:\ElainaBOT-main\tobz.js:676:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:42300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MFarelS** [comment]
Ketiknya Udah Bener?
#magernulis1 --Nama--Kelas--Text

**Comment by akujeleksad** [comment]
udah bener

**Comment by akujeleksad** [comment]
tapi tetep ga bisa kumaha

**Comment by TobyG74** [comment]
join grup wa aja

**Comment by akujeleksad** [comment]
link?
