### ISSUE TITLE
anjay eror lagi

### ISSUE THREAD

**Issue by akujeleksad** [TobyG74/ElainaBOT#78]
C:\ElainaBOT-main\tobz.js:1540
            const { potensi, koordinat, lokasi, kedalaman, magnitude, waktu, map } = bmkg.data
                                                                      ^

SyntaxError: Identifier 'waktu' has already been declared

**Comment by akujeleksad** [comment]
node:62296) UnhandledPromiseRejectionWarning: Error: Cannot find file. Make sure the file reference is relative, a valid URL or a valid DataURL
    at Client.<anonymous> (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:916:35)
    at step (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\ElainaBOT-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:900:16)
    at ChildProcess.<anonymous> (C:\ElainaBOT-main\tobz.js:677:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:62296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


ini eror kenapa oiiii
